[package]
name = "bracket-geometry"
version = "0.7.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"
publish = true
description = "Geometry utilities. Rect, lines, circles, distance calculations. Part of the bracket-lib family."
homepage = "https://github.com/thebracket/rltk_rs"
repository = "https://github.com/thebracket/rltk_rs"
readme = "README.md"
keywords = ["geometry", "gamedev", "bresenham", "circle", "distance"]
categories = ["game-engines", "graphics"]
license = "MIT"

[dependencies]
ultraviolet = "0.4.5"
serde = { version = "1.0.104", features = ["derive"], optional = true }
specs = { version = "0.16.1", optional = true }

[dev-dependencies]
crossterm = "0.16.0"
