[package]
name = "rltk"
version = "0.5.2"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"
publish = false
description = "A CP437/ASCII terminal library and helpers to make creating roguelike games in Rust easy. Similar to libtcod, but aiming to be Rust-native."
homepage = "https://github.com/thebracket/rltk_rs"
repository = "https://github.com/thebracket/rltk_rs"
readme = "README.md"
keywords = ["roguelike", "cp437", "ascii", "virtual terminal", "gamedev"]
categories = ["game-engines", "graphics"]
license = "MIT"
maintenance = { status = "actively-developed" }

[dependencies]
glow = "0.3.0-alpha2"
image = { version = "0.22.3", default-features = false, features = ["jpeg", "png_codec"] }
cgmath = "0.17.0"
bresenham = "0.1.1"
rand_xorshift = "0.2.0"
serde= { version = "1.0.101", features = ["derive"], optional = true }
serde_json =  { version = "1.0.41", optional = true }
flate2 = "1.0.12"
byteorder = "1.3.2"
lazy_static = "1.4.0"

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
glutin = "0.22.0-alpha3"
rayon = "1.1.0"
rand = "0.7.2"

[target.wasm32-unknown-unknown.dependencies]
web-sys = { version = "0.3", features=["console", "Attr", "CanvasRenderingContext2d", "Document", "Element", "Event",
    "EventTarget", "HtmlCanvasElement", "HtmlElement", "HtmlInputElement", "Node", "Text", "Window", "KeyboardEvent",
    "MouseEvent"] }
wasm-bindgen = "0.2"
wasm-timer = "0.1.0"
rand = { version = "0.7.2", features = ["wasm-bindgen"] }

[dev-dependencies]
specs = "0.15.1"

[build-dependencies]
gl_generator = "0.14.0"

[features]
default = []
serialization = [ "serde/derive", "serde_json" ]

